### ISSUE TITLE
1.10.2 - 9.2.0.291 - game crashes on load after updated from 290 to 291

### ISSUE THREAD

**Issue by LordHellscream** [aidancbrady/Mekanism#3763]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.57-universal.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.291.jar)
  CCCDeobfPlugin (unknown)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.51-beta.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 9/6/16 9:51 PM
Description: Tesselating block model

java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at mekanism.common.multipart.ConnectionProperty.valueToString(ConnectionProperty.java:48)
	at mekanism.client.render.obj.TransmitterModel.func_188616_a(TransmitterModel.java:135)
	at mcmultipart.client.multipart.ModelMultipartContainer.func_188616_a(ModelMultipartContainer.java:68)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:171)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:951)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mekanism.common.multipart.ConnectionProperty.valueToString(ConnectionProperty.java:48)
	at mekanism.client.render.obj.TransmitterModel.func_188616_a(TransmitterModel.java:135)
	at mcmultipart.client.multipart.ModelMultipartContainer.func_188616_a(ModelMultipartContainer.java:68)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)

-- Block model being tesselated --
Details:
	Block: mcmultipart:multipart[ticking=true]
	Block location: World: (313,60,160), Chunk: (at 9,3,0 in 19,10; contains blocks 304,0,160 to 319,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)

-- Block being tesselated --
Details:
	Block type: ID #693 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (313,60,160), Chunk: (at 9,3,0 in 19,10; contains blocks 304,0,160 to 319,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:171)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:951)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['LordHellscream'/167, l='MpServer', x=307.75, y=60.00, z=160.91]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (305,60,161), Chunk: (at 1,3,1 in 19,10; contains blocks 304,0,160 to 319,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3531456 game time, 3731979 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 90 total; [EntityZombie['Zombie'/128, l='MpServer', x=366.78, y=50.00, z=118.48], EntitySpider['Spider'/129, l='MpServer', x=366.70, y=26.00, z=197.30], EntityPig['Pig'/130, l='MpServer', x=367.80, y=63.00, z=195.27], EntitySkeleton['Skeleton'/131, l='MpServer', x=369.50, y=27.00, z=113.91], EntityZombie['Zombie'/132, l='MpServer', x=373.50, y=38.00, z=169.50], EntitySkeleton['Skeleton'/133, l='MpServer', x=381.49, y=32.00, z=162.85], EntityPig['Pig'/134, l='MpServer', x=372.55, y=63.00, z=160.45], EntityZombie['Zombie'/135, l='MpServer', x=369.50, y=49.00, z=168.50], EntityChicken['Chicken'/136, l='MpServer', x=377.68, y=64.00, z=174.56], EntityPig['Pig'/137, l='MpServer', x=375.55, y=62.00, z=177.55], EntityPig['Pig'/138, l='MpServer', x=372.27, y=63.00, z=188.59], EntityPig['Pig'/139, l='MpServer', x=369.53, y=63.00, z=182.75], EntityPig['Pig'/140, l='MpServer', x=368.33, y=63.00, z=192.99], EntityZombie['Zombie'/141, l='MpServer', x=370.50, y=33.54, z=220.62], EntityCreeper['Creeper'/142, l='MpServer', x=370.50, y=36.00, z=212.50], EntitySkeleton['Skeleton'/14, l='MpServer', x=230.50, y=35.00, z=93.50], EntitySkeleton['Skeleton'/17, l='MpServer', x=228.50, y=39.00, z=160.50], EntityCreeper['Creeper'/146, l='MpServer', x=384.50, y=23.00, z=164.19], EntityChicken['Chicken'/18, l='MpServer', x=233.84, y=67.00, z=226.71], EntityBat['Bat'/148, l='MpServer', x=385.92, y=33.22, z=186.93], EntitySkeleton['Skeleton'/149, l='MpServer', x=386.70, y=56.00, z=180.70], EntityZombie['Zombie'/150, l='MpServer', x=385.51, y=23.00, z=209.13], EntityCreeper['Creeper'/151, l='MpServer', x=385.50, y=23.00, z=208.07], EntityCreeper['Creeper'/27, l='MpServer', x=244.50, y=11.00, z=96.50], EntitySkeleton['Skeleton'/28, l='MpServer', x=241.50, y=35.00, z=165.50], EntitySquid['Squid'/29, l='MpServer', x=252.25, y=61.62, z=212.23], EntityBat['Bat'/30, l='MpServer', x=246.75, y=28.50, z=233.19], EntitySquid['Squid'/35, l='MpServer', x=256.30, y=56.00, z=132.60], EntitySquid['Squid'/36, l='MpServer', x=261.34, y=62.47, z=151.47], EntityBabySkeleton['Baby Skeleton'/37, l='MpServer', x=265.50, y=15.00, z=162.50], EntityBat['Bat'/38, l='MpServer', x=264.75, y=16.10, z=170.41], EntityChicken['Chicken'/39, l='MpServer', x=258.78, y=62.61, z=173.87], EntityChicken['Chicken'/40, l='MpServer', x=270.15, y=70.00, z=173.82], EntityItem['item.item.egg'/41, l='MpServer', x=270.88, y=70.00, z=173.13], EntityPlayerSP['LordHellscream'/167, l='MpServer', x=307.75, y=60.00, z=160.91], EntityZombie['Zombie'/45, l='MpServer', x=286.50, y=41.00, z=153.50], EntityBat['Bat'/46, l='MpServer', x=286.75, y=42.10, z=153.75], EntityZombie['Zombie'/47, l='MpServer', x=282.56, y=48.00, z=152.81], EntityZombie['Zombie'/48, l='MpServer', x=281.84, y=48.00, z=153.10], EntitySkeleton['Skeleton'/49, l='MpServer', x=281.30, y=48.00, z=152.30], EntityCreeper['Creeper'/50, l='MpServer', x=285.22, y=18.00, z=166.58], EntityZombie['Zombie'/51, l='MpServer', x=283.56, y=46.00, z=164.79], EntityBat['Bat'/52, l='MpServer', x=279.75, y=49.10, z=162.75], EntityZombie['Zombie'/53, l='MpServer', x=286.70, y=20.00, z=182.70], EntityZombie['Zombie'/54, l='MpServer', x=285.50, y=20.00, z=184.20], EntitySkeleton['Skeleton'/55, l='MpServer', x=275.53, y=47.00, z=201.28], EntityZombie['Zombie'/56, l='MpServer', x=284.35, y=22.00, z=218.35], EntityCreeper['Creeper'/57, l='MpServer', x=275.50, y=40.00, z=224.50], EntitySquid['Squid'/62, l='MpServer', x=296.26, y=55.00, z=111.25], EntitySkeleton['Skeleton'/63, l='MpServer', x=291.50, y=13.00, z=154.50], EntityZombie['Zombie'/64, l='MpServer', x=298.29, y=36.00, z=149.36], EntityCreeper['Creeper'/65, l='MpServer', x=297.52, y=36.00, z=150.21], EntityZombie['Zombie'/66, l='MpServer', x=296.59, y=39.00, z=150.80], EntityCreeper['Creeper'/67, l='MpServer', x=293.82, y=37.00, z=159.39], EntityCreeper['Creeper'/68, l='MpServer', x=306.38, y=37.00, z=146.30], EntityBat['Bat'/69, l='MpServer', x=316.75, y=39.10, z=147.88], EntityBat['Bat'/70, l='MpServer', x=318.75, y=41.10, z=155.35], EntityRobit['G2'/71, l='MpServer', x=307.52, y=60.00, z=159.14], EntitySkeleton['Skeleton'/72, l='MpServer', x=316.30, y=37.00, z=166.23], EntityCreeper['Creeper'/73, l='MpServer', x=318.30, y=35.00, z=174.66], EntitySkeleton['Skeleton'/74, l='MpServer', x=316.85, y=37.00, z=166.88], EntityZombie['Zombie'/75, l='MpServer', x=311.52, y=45.00, z=164.80], EntityEnderman['Enderman'/76, l='MpServer', x=309.53, y=45.00, z=167.52], EntityZombie['Zombie'/77, l='MpServer', x=301.70, y=29.00, z=166.70], EntityBat['Bat'/78, l='MpServer', x=290.25, y=39.10, z=179.54], EntitySpider['Spider'/79, l='MpServer', x=296.50, y=45.00, z=204.50], EntityCreeper['Creeper'/91, l='MpServer', x=311.50, y=25.00, z=137.50], EntityBat['Bat'/92, l='MpServer', x=314.25, y=50.10, z=178.75], EntityBat['Bat'/93, l='MpServer', x=311.52, y=53.10, z=187.25], EntityZombie['Zombie'/99, l='MpServer', x=325.77, y=52.00, z=159.51], EntityZombie['Zombie'/100, l='MpServer', x=327.30, y=47.00, z=170.30], EntitySpider['Spider'/101, l='MpServer', x=320.30, y=36.00, z=168.87], EntitySkeleton['Skeleton'/102, l='MpServer', x=329.50, y=50.00, z=169.50], EntityBat['Bat'/103, l='MpServer', x=321.47, y=55.10, z=164.75], EntityCreeper['Creeper'/104, l='MpServer', x=321.78, y=53.00, z=167.97], EntityCreeper['Creeper'/105, l='MpServer', x=321.81, y=54.00, z=166.60], EntityCreeper['Creeper'/106, l='MpServer', x=322.71, y=54.00, z=169.70], EntityEnderman['Enderman'/107, l='MpServer', x=323.70, y=54.00, z=167.30], EntityZombie['Zombie'/108, l='MpServer', x=320.21, y=53.00, z=170.56], EntityBat['Bat'/109, l='MpServer', x=324.43, y=61.10, z=177.94], EntityPig['Pig'/110, l='MpServer', x=334.55, y=63.00, z=205.55], EntityChicken['Chicken'/111, l='MpServer', x=327.89, y=63.00, z=210.62], EntityItem['item.item.egg'/112, l='MpServer', x=329.19, y=63.00, z=211.43], EntitySkeleton['Skeleton'/120, l='MpServer', x=337.50, y=6.00, z=114.50], EntityZombie['Zombie'/121, l='MpServer', x=339.14, y=4.00, z=115.55], EntityZombie['Zombie'/122, l='MpServer', x=337.92, y=46.00, z=175.41], EntityChicken['Chicken'/123, l='MpServer', x=337.65, y=52.00, z=165.49], EntityChicken['Chicken'/124, l='MpServer', x=344.20, y=63.27, z=181.43], EntitySkeleton['Skeleton'/126, l='MpServer', x=357.50, y=47.00, z=109.50], EntityBat['Bat'/127, l='MpServer', x=360.97, y=31.66, z=108.32]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1523028120 bytes (1452 MB) / 3001966592 bytes (2862 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.1.2073 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2073.jar) 
	UCHIJAAAA	Forge{12.18.1.2073} [Minecraft Forge] (forge-1.10.2-12.18.1.2073.jar) 
	UCHIJAAAA	CodeChickenCore{2.1.8.79} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r60} [Actually Additions] (ActuallyAdditions-1.10.2-r60.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2068} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2068-universal.jar) 
	UCHIJAAAA	capsule{1.10.2-1.2.0} [Capsule] (Capsule-1.10.2-1.2.0.jar) 
	UCHIJAAAA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJAAAA	ChickenChunks{2.1.3.36} [ChickenChunks] (ChickenChunks-1.10.2-2.1.3.36-universal.jar) 
	UCHIJAAAA	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-MC1.9.4-0.0.6.33.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.51-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.51-beta.jar) 
	UCHIJAAAA	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1.jar) 
	UCHIJAAAA	immersiveengineering{${version}} [Immersive Engineering] (ImmersiveEngineering-0.10-40.jar) 
	UCHIJAAAA	JEI{3.9.0.244} [Just Enough Items] (jei_1.10.2-3.9.0.244.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.95_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.95_beta.jar) 
	UCHIJAAAA	shetiphiancore{3.3.0} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.0.jar) 
	UCHIJAAAA	endertanks{1.4.1} [EnderTanks] (endertanks-1.10.0-1.4.1.jar) 
	UCHIJAAAA	enderthing{0.6.11} [Enderthing] (enderthing-1.10.2-0.6.11.jar) 
	UCHIJAAAA	ExtendAHand{1.3} [Extend-A-Hand] (ExtendAHand-1.10.2-1.3.jar) 
	UCHIJAAAA	furnus{1.83} [Furnus] (Furnus-1.10.2-1.83.jar) 
	UCHIJAAAA	giacomosfoundry{1.3.5} [Giacomo's Foundry] (GiacomosFoundry1.10.2-1.3.5.jar) 
	UCHIJAAAA	grapplemod{1.10-v7} [Grappling hook mod] (grapplemod-1.10.2-v7.jar) 
	UCHIJAAAA	HealthBar{1.0.3} [Health Bar] (HealthBar-1.9.4-1.0.3-14.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJAAAA	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	UCHIJAAAA	Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.291.jar) 
	UCHIJAAAA	MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.291.jar) 
	UCHIJAAAA	MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.291.jar) 
	UCHIJAAAA	notenoughwands{1.3.5} [Not Enough Wands] (notenoughwands-1.9.4-1.3.5.jar) 
	UCHIJAAAA	parachutemod{1.5.2} [Parachute Mod] (parachutemod-ng-1.10.2-1.5.2-409.jar) 
	UCHIJAAAA	PersistentBits{1.0.3} [Persistent Bits] (PersistentBits-1.10.2-1.0.3.jar) 
	UCHIJAAAA	progressiveautomation{1.6.49} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.49.jar) 
	UCHIJAAAA	RandomUtilities{3.1.1} [Random Utilities] (Random Utilities-1.9.4-3.1.1.jar) 
	UCHIJAAAA	randomthings{3.7.5} [Random Things] (RandomThings-MC1.10.2-3.7.5.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.2.6} [Storage Drawers] (StorageDrawers-1.10.2-3.2.6.jar) 
	UCHIJAAAA	refinedstorage{0.8.20} [Refined Storage] (refinedstorage-0.8.20.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.496} [Reliquary] (Reliquary-1.10.2-1.3.3.496.jar) 
	UCHIJAAAA	rftools{5.17} [RFTools] (rftools-1.10-5.17.jar) 
	UCHIJAAAA	rftoolsdim{4.30beta48} [RFTools Dimensions] (rftoolsdim-1.10-4.30beta48.jar) 
	UCHIJAAAA	roots{0.112} [Roots] (roots-1.10.2-0.112.0.jar) 
	UCHIJAAAA	storagenetwork{1.12.8} [Storage Network] (StorageNetwork-1.9.4-1.12.8.jar) 
	UCHIJAAAA	storagesilo{1.2.2} [StorageSilo] (storagesilo-1.9.4-1.2.2b.jar) 
	UCHIJAAAA	thutcore{4.0.0} [ThutCore] (thutcore-1.10.2-4.0.0.jar) 
	UCHIJAAAA	thuttech{3.0.9} [Thut's Tech] (thuttech-3.0.9.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.57-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.291.jar)
  
CCCDeobfPlugin (unknown)
  
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.51-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 365.19' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	CodeChickenCore: ignoreInvalidMCVersion state: false
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/Mekanism-1.10.2-9.2.0.291.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/Mekanism-1.10.2-9.2.0.291.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/Mekanism-1.10.2-9.2.0.291.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/Mekanism-1.10.2-9.2.0.291.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/Mekanism-1.10.2-9.2.0.291.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/Mekanism-1.10.2-9.2.0.291.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/Mekanism-1.10.2-9.2.0.291.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/Mekanism-1.10.2-9.2.0.291.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/Mekanism-1.10.2-9.2.0.291.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Pak/AppData/Roaming/.minecraft/instances/Forge1.9/mods/Mekanism-1.10.2-9.2.0.291.jar!/cofh/api/energy/TileEnergyHandler.class

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2073
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 365.19, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.10.2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz

**Comment by K1ltu** [comment]
I got the same Crash when placing universal cable

http://pastebin.com/4sADqtsH


MC 1.10.2
Forge 2053
Mekanism-1.10.2-9.2.0.291

**Comment by UnPure** [comment]
I can confirm this.
Tested it on Forge 12.18.1.2076
Mekanism, MekanismTools and MekanismGenerators  v9.2.0.291
No other mods (besides mcmultipart which is auto downloaded).

Crashlog: http://pastebin.com/7yDcSQSx

The issue could be related to https://github.com/aidancbrady/Mekanism/issues/3694

Steps to reproduce:
Install Forge 2076, install Mekanism, load a new world and place a mechanical pipe.

**Comment by MrNinja93** [comment]
Also getting it,  Mekanism McMultiPart compatible blocks, cables pipes etc existing and newly placed.

**Comment by aidancbrady** [comment]
Should be fixed on build 292.

**Comment by accessdenied0** [comment]
@aidancbrady,

It might be a stupid question but where can I look at the Changelog, to know what changed? I didn't found it so far.

access_denied

**Comment by UnPure** [comment]
@accessdenied0 
http://ci.indiewikis.com:8080/job/Mekanism/
Just click on the build number on the left side to take a look at the changes. ;)

**Comment by accessdenied0** [comment]
@UnPure 

Thank you! I just didn't know where to find it.
